from sqlalchemy import Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.sql import func
from app.db.database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    phone_number = Column(String, unique=True, index=True, nullable=False)
    full_name = Column(String, nullable=True)
    role = Column(String, default="customer")  # "customer" or "worker"
    dob = Column(String, nullable=True)
    gender = Column(String, nullable=True)
    offered_services = Column(String, nullable=True)  # JSON list or comma-separated string of subCategory IDs
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Booking(Base):
    __tablename__ = "bookings"

    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    worker_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    service_id = Column(String(50), nullable=False)
    date = Column(String(10), nullable=False)       # YYYY-MM-DD
    time_slot = Column(String(20), nullable=False)  # e.g. "14:00-15:00"
    status = Column(String(20), default="pending")  # pending | accepted | in_progress | completed | cancelled
    address = Column(String, nullable=True)
    amount = Column(String(20), nullable=True)       # price string e.g. "299"
    start_otp = Column(String(6), nullable=True)    # generated by worker at job site to start
    end_otp = Column(String(6), nullable=True)      # generated by worker to close job
    otp = Column(String(6), nullable=True)          # legacy, kept for migration compat
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), nullable=True)
