# Generated by Django 6.0.1 on 2026-06-30 11:52

import django.db.models.deletion
import djangoapp.models
import phonenumber_field.modelfields
import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='fullName')),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('N', 'rather not say')], default=('M', 'Male'), max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(default='nagpur', null=True)),
                ('geo_location', models.CharField(null=True)),
                ('work_id', models.UUIDField(blank=True, null=True)),
                ('temp_id', models.UUIDField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('imageURL', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=djangoapp.models.upload_worker_image)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_working', models.BooleanField(default=False, null=True)),
                ('is_online', models.BooleanField(default=False, null=True)),
                ('work_id', models.UUIDField(blank=True, null=True)),
                ('temp_id', models.UUIDField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('N', 'rather not say')], default=('N', 'rather not say'))),
                ('location', models.CharField(default='', null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('categories', models.CharField(default='electrician')),
                ('sub_categories', models.JSONField(default=djangoapp.models.initialize_items)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('his_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=30)),
                ('timestmp', models.DateTimeField(auto_now=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('geo_location', models.CharField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyRecords', to='djangoapp.customer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.worker')),
            ],
        ),
    ]
