# Generated by Django 6.0.1 on 2026-03-01 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0023_alter_worker_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='worker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='djangoapp.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='location',
            field=models.CharField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
