# Generated by Django 6.0.1 on 2026-03-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0024_history_worker_worker_location_worker_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='uid',
        ),
    ]
