# Generated by Django 6.0.1 on 2026-03-03 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0026_alter_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='work_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='is_finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
