# Generated by Django 6.0.1 on 2026-03-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0027_customer_is_online_customer_is_working_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='rates',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='location',
            field=models.CharField(default='nagpur', null=True),
        ),
    ]
