# Generated by Django 6.0.1 on 2026-03-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0028_worker_rates_alter_worker_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='price',
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
