# Generated by Django 6.0.1 on 2026-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0029_remove_worker_price_alter_worker_work_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('N', 'rather not say')], default=('N', 'rather not say')),
        ),
        migrations.AlterField(
            model_name='worker',
            name='rates',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
