# Generated by Django 6.0.1 on 2026-03-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0030_alter_worker_gender_alter_worker_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='category',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_Consult',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_Fixed',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_Hourly',
        ),
    ]
