# Generated by Django 6.0.1 on 2026-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0031_remove_worker_category_remove_worker_is_consult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='sub_categories',
            field=models.JSONField(default=dict),
        ),
    ]
