# Generated by Django 6.0.1 on 2026-03-12 15:19

import djangoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0032_worker_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='sub_categories',
            field=models.JSONField(default=djangoapp.models.initialize_items),
        ),
    ]
